### ISSUE TITLE
Building extension

### ISSUE THREAD

**Issue by noteven** [guilhermehn/manga-reader#10]
The README should probably clarify that one needs to create the build directory before running the 'npm install'. Furthermore, I cannot seem to run 'npm run js' as 'browserify .' fails. Having glanced over the browserify-handbook documentation and main page I can find no use of running browserify on directories, though this may be my own oversight.

**Comment by guilhermehn** [comment]
You're right, I was using gulp before moving to browserify and gulp create non-existent directories by itself, but browserify does not. I will fix it asap.
