### ISSUE TITLE
Find a better way to host the websites implementations

### ISSUE THREAD

**Issue by guilhermehn** [guilhermehn/manga-reader#2]

**Comment by KriPet** [comment]
One way that I see a lot of projects using, is creating a seperate github repo for config files.

Example: https://github.com/KSP-CKAN

This has the added bonus of it being easy to create PRs to fix websites.

PS: Thanks for working on this.

**Comment by guilhermehn** [comment]
Agreed, seems the best approach, the only downside compared to the actual method is a extension update with each implementation change. But it's not that bad if we consider that websites does not update their code that much.

**Comment by Shados** [comment]
@guilhermehn: To avoid that, you could store them in a separate repo as suggested and have the addon download the raw files from github at run-time.

**Comment by guilhermehn** [comment]
@Shados It already does it today, but downloading scripts and evaluating then on the fly gives me goosebumps :worried:
